on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo ${{GITHUB_ACTION_PATH}}
        shell: bash
      - uses: actions/checkout@v3
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
