# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - uses: actions/checkout@v3
#       - name: run composit action
#         uses: ./.github/composit-action
#         with:
#          who-to-greet: 'dharmajeet'         
#       - run: echo random-number ${{ steps.foo.outputs.random-number }}
#         shell: bash


on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: run composit action
        uses: dharmajeet/github-composit-action@v1.1.1
        with:
         who-to-greet: 'dharmajeet'         
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
