on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo {{GITHUB_ACTION_PATH}}
        shell: bash
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/github-composit-action@v1
        with:
          who-to-greet: 'Dharmajeet'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
